### ISSUE TITLE
General - Discuss about branch strategy in Github

### ISSUE THREAD

**Issue by mbahaloo2022** [global-climate/.github#1]
- [ ] https://www.engati.com/blog/git-branching-strategies

[drawio-git-branching-models.zip](https://github.com/global-climate/.github/files/15345171/drawio-git-branching-models.zip)

Also an related open topic: version in the maven files

**Comment by mbahaloo2022** [comment]
- [ ] https://www.engati.com/blog/git-branching-strategies

**Comment by rjuergen** [comment]
Branching model suggestions A:
![git-branching-model drawio](https://github.com/global-climate/.github/assets/15914636/0ab8e30d-c890-4fb5-b8b3-b31d11d49607)
main = dev system
demo = demo system
latest-release tag = prod system
feat/csrd/main = an not yet stable feature with multiple outgoing feature branches

**Comment by rjuergen** [comment]
Branching model suggestion B:
![git-branching-model-v2 drawio](https://github.com/global-climate/.github/assets/15914636/62c1b082-1a4b-4138-9242-bc04726c601f)
main = dev system
release = demo system
latest-release tag = prod system
feat/csrd/main = an not yet stable feature with multiple outgoing feature branches

**Comment by sfmohassel** [comment]
Interesting topic 👍   Specially with the diagrams (@rjuergen which tools did you use to create the diagrams 😄 )

In choosing a branching strategy, I think we should consider these topics:

## Need to develop system

We do not have yet automated end-to-end testing that tests frontend with backend together and I really cannot picture us having that this year, unless feature-development speed is reduced. This means that we cannot eliminate the need for a _develop system_ where developers can test latest features.

## Demo gets commits from develop and production

Our demo system is a place where we can test _latest features AND hot fixes_ before going live on production. This mixture of new features + hot fixes means that demo system gets new commits from either a hot fix on production or from develop system.

## Infrastructure considerations

### Creating a hot fix

For hot fixes we can as usual create a new branch from latest tag, because anyways we always want to fix the latest 
version of our software. This means we do not need to be careful about anything special, so infrastructure code-review will not become more time-consuming.

### Reverting to a previous version

If we ever need to revert to an older version (in either production or demo systems) we should find a way to deploy a specific git tag in AWS. Though, _this is something that will force our AWS setup to change_.

### Adding new features

I do not think that this will add any new complexity to our infrastructure. We just need to ensure that _we modify our AWS setup in a way that it deploys a certain commit and not the latest changes from the release branch._

## My vote

I think currently we are following Git-flow strategy (next picture depicts git-flow strategy). With one exception: to us, `develop` and `master` branches from the picture below are the same and we call it `main`. It means we do not hold a clean deployable master branch with tags. I personally have no issue with multiple release branches instead of one branch with tags.

![image](https://github.com/global-climate/.github/assets/20520614/619c586b-420f-4f19-9cf0-ca01234fe49f)

I also humbly think that other colleagues from the team should also be involved in this and give feedback as well :-)

**Comment by rjuergen** [comment]
I used draw.io
Here are the files to import if you wanna use them as a template to create your own: [drawio-git-branching-models.zip](https://github.com/global-climate/.github/files/15345171/drawio-git-branching-models.zip)

**Comment by rjuergen** [comment]
Branching model suggestion C:
![git-branching-model-v3 drawio](https://github.com/global-climate/.github/assets/15914636/60c13b26-6100-4fd2-874e-78db44486e68)

main = dev system
release = demo system
latest-release (or active-release) tag = prod system
csrd/main = an **not stable** feature with multiple outgoing feature branches

[git-branching-model-v3.zip](https://github.com/user-attachments/files/15759454/git-branching-model-v3.zip)

**Comment by sfmohassel** [comment]
I could **not** 😨  assign other colleagues to this issue so that they express their understanding and potential solutions, so I tag the whole team: @global-climate/gc-developers 

Also, I could not mention them individually!
